return {
	["1"] = {title = "Kill NPC", des = "Instantly kill the NPC", val = 15},
	["2"] = {title = "Bring NPC", des  = "Teleport the NPC to your position"},
	["3"] = {title = "Goto NPC", des = "Teleport your character to the NPC's position"},
	["4"] = {title = "Control NPC", des = "Take control of the NPC until network ownership is lost"},
	["5"] = {title = "Punish NPC", des = "Make the NPC disappear into space"},
	["6"] = {title = "NPC Sit State", des = "Force the NPC into a sitting position"},
	["7"] = {title = "NPC Jump State", des = "Make the NPC jump", val = 3},
	["8"] = {title = "Follow NPC", des = "Make the NPC follow you"},
	["9"] = {title = "Kill Aura (Any NPC)", val = 15},
	["10"] = {title = "Jump Aura (Any NPC)", val = 3}
}
